import { describe, it, expect } from "vitest"
import { buildPrompt } from "./prompts"
import type { ConversionOptions } from "./types"

const NONE: ConversionOptions = { responsive: false, semanticHtml: false, darkMode: false, a11y: false }
const ALL: ConversionOptions = { responsive: true, semanticHtml: true, darkMode: true, a11y: true }

describe("buildPrompt", () => {
  it("names the framework and the role", () => {
    expect(buildPrompt("react-tsx", NONE)).toContain("react-tsx")
    expect(buildPrompt("react-tsx", NONE).toLowerCase()).toContain("senior frontend engineer")
  })

  it("always embeds the critical output rules and SliceUI marker", () => {
    const p = buildPrompt("tailwind", NONE)
    expect(p).toContain("// Generated by SliceUI")
    expect(p).toContain("Self-contained component")
    expect(p.toLowerCase()).toContain("hex")
  })

  it("omits conditional option rules when disabled", () => {
    const p = buildPrompt("tailwind", NONE)
    expect(p).not.toContain("responsive breakpoints")
    expect(p).not.toContain("aria-label")
  })

  it("adds the option rules only when enabled", () => {
    const p = buildPrompt("react-tsx", ALL)
    expect(p).toContain("responsive breakpoints")
    expect(p).toContain("semantic HTML5")
    expect(p).toContain("dark mode")
    expect(p).toContain("aria-label")
  })

  it("includes framework-specific rules", () => {
    expect(buildPrompt("vue-sfc", NONE)).toContain("Composition API")
    expect(buildPrompt("bootstrap5", NONE)).toContain("container/row/col")
    expect(buildPrompt("native-html", NONE)).toContain("CSS custom properties")
  })
})
