import type { Framework, ConversionOptions } from "./types"

export function buildPrompt(framework: Framework, options: ConversionOptions): string {
  const optionRules = []

  if (options.responsive) {
    optionRules.push("- Add responsive breakpoints (mobile-first, sm: md: lg:)")
  }
  if (options.semanticHtml) {
    optionRules.push("- Use semantic HTML5 elements (nav, main, section, article, header, footer)")
  }
  if (options.darkMode) {
    optionRules.push("- Include dark mode variant using prefers-color-scheme or dark: prefix")
  }
  if (options.a11y) {
    optionRules.push("- Add aria-label, role, and alt attributes from visual context")
  }

  const optionRulesText = optionRules.length > 0 ? optionRules.join("\n") : ""

  return `You are a senior frontend engineer. Analyze this UI screenshot and generate production-ready ${framework} component code.

CRITICAL OUTPUT RULES:
1. Output ONLY the component code. No explanation, no markdown fences.
   First character of your response must be the first character of the code.
2. Self-contained component — not a full app. No html/body/main entry points.
3. Use the exact text visible in the image as placeholder content.
4. For images in the UI: use a gray div with descriptive alt text.
5. For icons: use a comment /* icon: {description} */ as placeholder.
6. Match colors from the image exactly using hex values.
7. First line must be: // Generated by SliceUI
${optionRulesText ? `\n${optionRulesText}` : ""}

FRAMEWORK: ${framework}
${getFrameworkRules(framework)}
`
}

function getFrameworkRules(framework: Framework): string {
  switch (framework) {
    case "tailwind":
      return `SPECIFIC RULES:
- Plain HTML fragment. Tailwind utility classes only.
- No <style> block. For custom hex not in Tailwind, use inline style only for that value.`

    case "react-tsx":
      return `SPECIFIC RULES:
- React functional component with TypeScript.
- Name it based on dominant type (HeroSection, NavBar, CardGrid, etc).
- Use className not class. Tailwind for styling. Export as default.`

    case "vue-sfc":
      return `SPECIFIC RULES:
- Vue 3 SFC with <template>, <script setup lang='ts'>, <style scoped>.
- Composition API. Tailwind classes in template.`

    case "bootstrap5":
      return `SPECIFIC RULES:
- Plain HTML. Bootstrap 5 class names only.
- Use container/row/col-* grid. Bootstrap utility classes (d-flex, gap-*, etc).`

    case "native-html":
      return `SPECIFIC RULES:
- Semantic HTML5 with <style> block at top.
- CSS custom properties for colors (--color-primary, --color-bg, etc).
- CSS Grid or Flexbox for layout. Zero framework dependencies.`

    case "nextjs":
      return `SPECIFIC RULES:
- Next.js App Router component. Add 'use client' only if has onClick/useState.
- Prefer Server Component. Use next/image for images. Tailwind. Export default.`

    case "svelte":
      return `SPECIFIC RULES:
- Svelte 5 component with runes ($state, $derived).
- <script lang='ts'>. Tailwind classes.`

    case "flutter":
      return `SPECIFIC RULES:
- Flutter StatelessWidget. Material 3.
- Color(0xFFHEXHEX) for colors. Column/Row/Expanded layout.
- Widget class only, not full app.`

    default:
      return ""
  }
}
