import { describe, it, expect } from "vitest";
import { buildPrompt } from "@/lib/prompts";
import type { ConversionOptions } from "@/lib/types";

const BASE_OPTIONS: ConversionOptions = {
  responsive: false,
  semanticHtml: false,
  darkMode: false,
  a11y: false,
};

describe("buildPrompt", () => {
  it("always emits the mandated first-line rule", () => {
    const prompt = buildPrompt("react-tsx", BASE_OPTIONS);
    expect(prompt).toContain("// Generated by SliceUI");
  });

  it("appends additional instructions when provided", () => {
    const prompt = buildPrompt("tailwind", BASE_OPTIONS, "Make it a pricing table");
    expect(prompt).toContain("Additional instructions: Make it a pricing table");
  });

  it("does not append an empty instructions line when omitted", () => {
    const prompt = buildPrompt("tailwind", BASE_OPTIONS);
    expect(prompt).not.toContain("Additional instructions:");
  });

  it("includes the design-system block when designSystem is set", () => {
    const options: ConversionOptions = {
      ...BASE_OPTIONS,
      designSystem: "--color-primary: #22c55e",
    };
    const prompt = buildPrompt("react-tsx", options);
    expect(prompt).toContain("<design_system>");
    expect(prompt).toContain("--color-primary: #22c55e");
    expect(prompt).toContain("</design_system>");
    expect(prompt).toContain("prioritize the design system");
  });

  it("omits the design-system block when designSystem is empty", () => {
    const prompt = buildPrompt("react-tsx", BASE_OPTIONS);
    expect(prompt).not.toContain("<design_system>");
  });
});
