// SliceUI /convert edge function (Deno). Run on Supabase Edge Functions.
//
// This is the metered, key-hiding proxy for image→code generation:
//   - authenticates the user from their Supabase JWT
//   - reads their entitlement (free | pro) from the `credits` table
//   - enforces the free daily limit OR the Pro credit balance
//   - routes free→Gemini, Pro→Claude (tiered quality)
//   - decrements Pro balance + writes usage_log
//
// Keys live in Deno env (server-side) — never shipped to the browser.
//
// Required env (set via `supabase secrets set`):
//   ANTHROPIC_API_KEY, GEMINI_API_KEY
// Optional env (defaults shown):
//   CLAUDE_MODEL=claude-sonnet-4-6   (use claude-opus-4-8 for a premium tier)
//   GEMINI_MODEL=gemini-2.0-flash
//   FREE_DAILY_LIMIT=5
// (SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY are injected by the runtime.)

// @ts-expect-error — Deno global, absent in the editor's TS env.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const FREE_DAILY_LIMIT = Number(Deno.env.get("FREE_DAILY_LIMIT") ?? 5);
const CLAUDE_MODEL = Deno.env.get("CLAUDE_MODEL") ?? "claude-sonnet-4-6";
const GEMINI_MODEL = Deno.env.get("GEMINI_MODEL") ?? "gemini-2.0-flash";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json",
};

const json = (body: unknown, status: number) =>
  new Response(JSON.stringify(body), { status, headers: cors });

// ── Prompt builder (server-authoritative; mirrors src/lib/prompts.ts) ─────────
// Duplicated because Deno can't import the Vite app's extension-less modules.
function frameworkRules(fw: string): string {
  switch (fw) {
    case "tailwind":
      return `SPECIFIC RULES:\n- Plain HTML fragment. Tailwind utility classes only.\n- No <style> block. For custom hex not in Tailwind, use inline style only for that value.`;
    case "react-tsx":
      return `SPECIFIC RULES:\n- React functional component with TypeScript.\n- Name it based on dominant type (HeroSection, NavBar, CardGrid, etc).\n- Use className not class. Tailwind for styling. Export as default.`;
    case "vue-sfc":
      return `SPECIFIC RULES:\n- Vue 3 SFC with <template>, <script setup lang='ts'>, <style scoped>.\n- Composition API. Tailwind classes in template.`;
    case "bootstrap5":
      return `SPECIFIC RULES:\n- Plain HTML. Bootstrap 5 class names only.\n- Use container/row/col-* grid. Bootstrap utility classes (d-flex, gap-*, etc).`;
    case "native-html":
      return `SPECIFIC RULES:\n- Semantic HTML5 with <style> block at top.\n- CSS custom properties for colors (--color-primary, --color-bg, etc).\n- CSS Grid or Flexbox for layout. Zero framework dependencies.`;
    case "nextjs":
      return `SPECIFIC RULES:\n- Next.js App Router component. Add 'use client' only if has onClick/useState.\n- Prefer Server Component. Use next/image for images. Tailwind. Export default.`;
    case "svelte":
      return `SPECIFIC RULES:\n- Svelte 5 component with runes ($state, $derived).\n- <script lang='ts'>. Tailwind classes.`;
    default:
      return "";
  }
}

function buildPrompt(fw: string, options: { responsive?: boolean; semanticHtml?: boolean; darkMode?: boolean; a11y?: boolean }): string {
  const opt: string[] = [];
  if (options.responsive) opt.push("- Add responsive breakpoints (mobile-first, sm: md: lg:)");
  if (options.semanticHtml) opt.push("- Use semantic HTML5 elements (nav, main, section, article, header, footer)");
  if (options.darkMode) opt.push("- Include dark mode variant using prefers-color-scheme or dark: prefix");
  if (options.a11y) opt.push("- Add aria-label, role, and alt attributes from visual context");
  const optText = opt.length ? `\n${opt.join("\n")}` : "";
  return `You are a senior frontend engineer. Analyze this UI screenshot and generate production-ready ${fw} component code.

CRITICAL OUTPUT RULES:
1. Output ONLY the component code. No explanation, no markdown fences.
   First character of your response must be the first character of the code.
2. Self-contained component — not a full app. No html/body/main entry points.
3. Use the exact text visible in the image as placeholder content.
4. For images in the UI: use a gray div with a descriptive alt text.
5. For icons: use a comment /* icon: {description} */ as placeholder.
6. Match colors from the image exactly (read them as hex values).
7. First line must be: // Generated by SliceUI

QUALITY REQUIREMENTS:
- Design tokens: consolidate the palette into reusable tokens (CSS custom variables
  like --color-primary, --color-bg, --radius, or the target framework's token
  convention). Reference tokens instead of repeating raw hex on every element.
- Repeated UI: if elements repeat (cards, list rows, nav links), extract ONE
  reusable sub-component and render the list by mapping over a typed data array.
- Naming: name the component from its function in PascalCase (Navbar, PricingCard).
- Elements: use the right element (<button> for actions, <a> for links, <ul>/<li>
  for lists, a single <h1> then ordered headings).
- Fidelity: preserve spacing rhythm, alignment, and visual hierarchy.
${optText}

FRAMEWORK: ${fw}
${frameworkRules(fw)}
`;
}

function clean(raw: string): string {
  return raw.replace(/^```[\w-]*\n?/m, "").replace(/```\s*$/m, "").trim();
}

// ── Provider calls (raw HTTP) ─────────────────────────────────────────────────
async function callGemini(base64: string, prompt: string): Promise<string> {
  const key = Deno.env.get("GEMINI_API_KEY");
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${key}`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }, { inline_data: { mime_type: "image/png", data: base64 } }] }],
    }),
  });
  if (!res.ok) throw new Error(`Gemini error ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("Gemini returned no content");
  return text as string;
}

async function callClaude(base64: string, prompt: string): Promise<string> {
  const key = Deno.env.get("ANTHROPIC_API_KEY");
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": key!,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 4096,
      messages: [{
        role: "user",
        content: [
          { type: "image", source: { type: "base64", media_type: "image/png", data: base64 } },
          { type: "text", text: prompt },
        ],
      }],
    }),
  });
  if (!res.ok) throw new Error(`Claude error ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const text = data?.content?.find((b: { type: string }) => b.type === "text")?.text;
  if (!text) throw new Error(`Claude returned no text (stop_reason=${data?.stop_reason ?? "?"})`);
  return text as string;
}

// ── Main ──────────────────────────────────────────────────────────────────────
// @ts-expect-error — Deno global.
Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);

  const authHeader = req.headers.get("Authorization") ?? "";
  const jwt = authHeader.replace(/^Bearer\s+/i, "");
  if (!jwt) return json({ error: "unauthorized" }, 401);

  const supabase = createClient(
    // @ts-expect-error — Deno global.
    Deno.env.get("SUPABASE_URL")!,
    // @ts-expect-error — Deno global.
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    { auth: { persistSession: false } },
  );

  const { data: { user } } = await supabase.auth.getUser(jwt);
  if (!user) return json({ error: "unauthorized" }, 401);

  let body: { image?: string; framework?: string; options?: Record<string, boolean> };
  try { body = await req.json(); } catch { return json({ error: "invalid_json" }, 400); }
  const { image, framework, options } = body;
  if (!image || !framework) return json({ error: "missing_image_or_framework" }, 400);

  // Entitlement
  const { data: credits } = await supabase.from("credits").select("*").eq("user_id", user.id).maybeSingle();
  const plan: "free" | "pro" = credits?.plan === "pro" ? "pro" : "free";
  const useClaude = plan === "pro";

  // Quota / balance
  if (plan === "free") {
    const today = new Date().toISOString().slice(0, 10);
    const { count } = await supabase
      .from("usage_log")
      .select("id", { count: "exact", head: true })
      .eq("user_id", user.id)
      .gte("created_at", today);
    if ((count ?? 0) >= FREE_DAILY_LIMIT) {
      return json({ error: "daily_limit_reached", message: `Free tier: ${FREE_DAILY_LIMIT} conversions/day. Upgrade for more.`, plan }, 429);
    }
  } else if ((credits?.balance ?? 0) <= 0) {
    return json({ error: "no_credits", message: "Out of credits — top up to continue.", plan }, 402);
  }

  const prompt = buildPrompt(framework, options ?? {});
  const model = useClaude ? "claude" : "gemini";
  try {
    const raw = useClaude ? await callClaude(image, prompt) : await callGemini(image, prompt);
    const code = clean(raw);

    // Meter: decrement Pro balance, log usage (best-effort, non-blocking).
    if (plan === "pro" && credits) {
      await supabase.from("credits").update({ balance: credits.balance - 1 }).eq("user_id", user.id);
    }
    await supabase.from("usage_log").insert({ user_id: user.id, framework, model, status: "success" });

    return json({ code, model, plan }, 200);
  } catch (err) {
    await supabase.from("usage_log").insert({ user_id: user.id, framework, model, status: "failed" });
    const message = err instanceof Error ? err.message : "Generation failed";
    return json({ error: "generation_failed", message, plan }, 500);
  }
});
