import type { VercelRequest, VercelResponse } from "@vercel/node"

// SliceUI — backend proxy for AI image→code (resolves ADR-001).
// Keys stay server-side; the browser never sees them. Vercel Hobby caps
// serverless functions at 60s, so the client mirrors that with a 55s timeout
// (see aiService.ts PROXY_TIMEOUT_MS).

export const config = {
  maxDuration: 60,
}

type ConvertBody = {
  base64Image: string
  framework: string
  options?: Record<string, unknown>
  instructions?: string
  mimeType?: string
}

type GeminiCandidate = {
  content?: { parts?: { text?: string }[] }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed" })
    return
  }

  const GEMINI_API_KEY = process.env.GEMINI_API_KEY
  if (!GEMINI_API_KEY) {
    res.status(500).json({ error: "Server AI key not configured" })
    return
  }

  let body: ConvertBody
  try {
    body = req.body as ConvertBody
  } catch {
    res.status(400).json({ error: "Invalid JSON body" })
    return
  }

  const { base64Image, framework, options, instructions, mimeType } = body
  if (!base64Image || !framework) {
    res.status(400).json({ error: "Missing base64Image or framework" })
    return
  }

  const prompt = buildPrompt(
    framework,
    (options as Record<string, unknown>) ?? {},
    instructions
  )

  try {
    const text = await callGemini(
      GEMINI_API_KEY,
      prompt,
      base64Image,
      mimeType ?? "image/png"
    )
    res.status(200).json({ code: clean(text) })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "AI request failed"
    console.error("proxy: gemini error:", message)
    res.status(502).json({ error: message })
  }
}

function buildPrompt(
  framework: string,
  options: Record<string, unknown>,
  instructions?: string
): string {
  const optionRulesText = [
    options.responsive ? "- Add responsive breakpoints (mobile-first)." : "",
    options.semanticHtml ? "- Use semantic HTML5 elements (nav, main, section, article)." : "",
    options.darkMode ? "- Include dark mode variant." : "",
    options.a11y ? "- Add aria-label, role, and alt attributes." : "",
  ]
    .filter(Boolean)
    .join("\n")

  const designSystemText = (options.designSystem as string)?.trim()
    ? `\nDesign system (prioritize this over other instructions):\n${options.designSystem}`
    : ""

  const instructionsText = instructions?.trim()
    ? `\nAdditional instructions: ${instructions.trim()}`
    : ""

  return `You are a senior frontend engineer. Analyze this UI screenshot and generate production-ready ${framework} component code.

CRITICAL OUTPUT RULES:
1. Output ONLY the component code. No explanation, no markdown fences.
   First character of your response must be the first character of the code.
2. Self-contained component — not a full app. No html/body/main entry points.
3. Use the exact text visible in the image as placeholder content.
4. For images in the UI: use a gray div with descriptive alt text.
5. For icons: use a comment /* icon: {description} */ as placeholder.
6. Match colors from the image exactly using hex values.
7. First line must be: // Generated by SliceUI

${optionRulesText ? `${optionRulesText}\n` : ""}${designSystemText}${instructionsText}

FRAMEWORK: ${framework}`
}

async function callGemini(
  apiKey: string,
  prompt: string,
  base64Image: string,
  mimeType: string
): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${encodeURIComponent(apiKey)}`

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            { text: prompt },
            { inline_data: { mime_type: mimeType, data: base64Image } },
          ],
        },
      ],
      generationConfig: { maxOutputTokens: 8192 },
    }),
  })

  if (!response.ok) {
    const errText = await response.text().catch(() => "")
    throw new Error(`Gemini API ${response.status}: ${errText.slice(0, 200)}`)
  }

  const data = (await response.json()) as {
    candidates?: GeminiCandidate[]
    error?: { message?: string }
  }

  if (data.error) {
    throw new Error(`Gemini error: ${data.error.message ?? "unknown"}`)
  }

  const text = data.candidates?.[0]?.content?.parts?.[0]?.text ?? ""
  if (!text) {
    throw new Error("Gemini returned no content")
  }
  return text
}

function clean(raw: string): string {
  return raw
    .replace(/^```[\w-]*\n?/m, "")
    .replace(/```\s*$/m, "")
    .trim()
}
